# Cosine Similarity with regular additions

In [1]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn import datasets
import numpy as np
import pandas as pd
from numpy import dot
from numpy.linalg import norm


df = pd.read_csv("/content/drive/MyDrive/Machine Learning/Iris.csv");
df = df[["SepalLengthCm","SepalWidthCm","PetalLengthCm","PetalWidthCm"]]

df.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [2]:
def cosine(x, y):
    dot_products = np.dot(x, y.T)
    norm_products = np.linalg.norm(x) * np.linalg.norm(y)
    return dot_products / (norm_products)

In [4]:
x = df.iloc[0:2].to_numpy()

for i in range(2,150):
  y = df.loc[i].to_numpy()
  ans = cosine(x,y)
  x = np.vstack([x, y])
  print(ans)

[0.73134186 0.6811769 ]
[0.60628446 0.56520016 0.55771517]
[0.53160847 0.49448867 0.4889207  0.4812316 ]
[0.46940811 0.43682377 0.43176943 0.42542462 0.46779502]
[0.41820603 0.38889357 0.38464214 0.3788244  0.41686347 0.45423127]
[0.39002772 0.36339457 0.35875843 0.3534318  0.38844946 0.42307256
 0.36221088]
[0.36396575 0.33944883 0.33481902 0.330084   0.3623874  0.39490126
 0.33797571 0.3577576 ]
[0.34719508 0.32405484 0.3193902  0.31481703 0.34554874 0.37628044
 0.32204264 0.34124996 0.29881094]
[0.33029183 0.30759056 0.30379411 0.2990679  0.32897469 0.3581067
 0.30666082 0.32440345 0.28380459 0.3114645 ]
[0.31145537 0.29002569 0.28648093 0.2824528  0.31032749 0.33820218
 0.28954231 0.30613823 0.26795151 0.2938927  0.32982366]
[0.29830291 0.27844833 0.27441285 0.27037737 0.29685014 0.32316149
 0.27659201 0.29313749 0.25665672 0.28191885 0.31589762 0.2865193 ]
[0.28793148 0.26793977 0.26480548 0.26048524 0.28683025 0.31198931
 0.26726209 0.28267942 0.24718566 0.2713282  0.30487361 0.2